"""primaty_key_upgrade

Revision ID: 111b30bb3006
Revises: fa81439cd608
Create Date: 2023-07-14 15:56:02.383355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111b30bb3006'
down_revision = 'fa81439cd608'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
