"""set primarykey

Revision ID: 2fabc487354d
Revises: 4668fb6f0ea0
Create Date: 2023-07-21 12:54:14.123659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fabc487354d'
down_revision = '4668fb6f0ea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
