"""primaty_key_upgrade2

Revision ID: 36e0fdb0038c
Revises: 111b30bb3006
Create Date: 2023-07-14 15:58:42.373450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e0fdb0038c'
down_revision = '111b30bb3006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
