"""tables upgrade

Revision ID: e4ce8b0c0573
Revises: a7cacac45f60
Create Date: 2023-07-12 18:39:36.242569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ce8b0c0573'
down_revision = 'a7cacac45f60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'parent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('user_chats', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chats', 'updated_at')
    op.alter_column('chats', 'parent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
