"""primaty_key_upgrade3

Revision ID: e5c79aea080b
Revises: 36e0fdb0038c
Create Date: 2023-07-14 16:02:24.764417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c79aea080b'
down_revision = '36e0fdb0038c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
