"""relationship upgrade

Revision ID: fa81439cd608
Revises: e4ce8b0c0573
Create Date: 2023-07-14 14:19:12.006702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa81439cd608'
down_revision = 'e4ce8b0c0573'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
